# Generated by Django 5.1.2 on 2024-10-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contactNumber', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('profilePicture', models.ImageField(upload_to='profile_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
